#define SIMD_PACKETSIZE     16
#define QUADPACKET_SIZE     64
// log2(64) = 6
#define LOG_QUADPACKETSIZE  6

#define READ_PREFETCH_START1(addr)
#define READ_PREFETCH_START2(addr)
#define WRITE_PREFETCH_START1(addr)
#define WRITE_PREFETCH_START2(addr)
#define PREFETCH_STOP1
#define PREFETCH_STOP2
